comet:
  project: "solAI"
  workspace: "YOUR_COMET_WORKSPACE"
  key: "YOUR_COMET_API_KEY"
data:
  data_path: "/code/data/classification/classification_annotations.csv"
model:
  registry: facebookresearch/dino:main
  name: dino_resnet50
  num_layers: 2
experiment:
  name_root: "02-02-2023"
  name: "${experiment.name_root}-${model.name}-${experiment.batch_size}-${experiment.learning_rate}-${experiment.optimizer}"
  batch_size: 12
  metric: "Loss"
  learning_rate: 0.0001
  weight_decay: 0.001
  optimizer: "Adam"
  unfreeze_at_beginning: False
  unfreeze_at_epoch: 5
  schedulers:
    - "plateau"
  checkpoint_dir: "/code/classification/experiments/models/"